version: '3.8'

services:
  db:
    image: postgres:17
    container_name: samiahomes_postgres_db
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - samiahomes_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.samiahomes
    environment:
    #   POSTGRES_DB: ${PROD_DATABASE_NAME}
    #   POSTGRES_USER: ${PROD_DATABASE_USER}
    #   POSTGRES_PASSWORD: ${PROD_DATABASE_PASSWORD}
      POSTGRES_DB: samia_homes_db
      POSTGRES_USER: samia_homes_user 
      POSTGRES_PASSWORD: Samiahomes11@#
    networks:
      - backend
   

  django-web:
    build:
      context: .
    container_name: samiahomes_django_web
    restart: always
    ports:
      - "8002:8000"
    depends_on:
      - db
    env_file:
      - .env.samiahomes
  
    environment:
      - PROD_DEBUG=True
      - PROD_ALLOWED_HOSTS=samiahomes.com,www.samiahomes.com,localhost,127.0.0.1,88.223.92.151
      - ENVIRONMENT=production
      - PROD_DATABASE_NAME=samia_homes_db
      - PROD_DATABASE_USER=samia_homes_user
      - PROD_DATABASE_PASSWORD=Samiahomes11@#
      - PROD_DATABASE_HOST=db
      - PROD_DATABASE_PORT=5432
      - DJANGO_SUPERUSER_EMAIL=admin@samiahomes.com
      - DJANGO_SUPERUSER_PASSWORD=Samiahomes11@#
    volumes:
      - /var/www/samia_homes/staticfiles:/var/www/samia_homes/staticfiles
      - /var/www/samia_homes/mediafiles:/var/www/samia_homes/mediafiles
    networks:
      - backend

    command: >
      sh -c "export DJANGO_SETTINGS_MODULE=msigana_ecommerce.settings.production &&
         python manage.py makemigrations &&
         python manage.py migrate &&
         python manage.py tailwind install &&
         python manage.py tailwind start &&
         python manage.py tailwind build && \
         python manage.py collectstatic --noinput &&
         (python manage.py createsuperuser --noinput --email admin@samiahomes.com  2>/dev/null || 
         echo \"[INFO] Superuser already exists - skipping creation\") &&
         gunicorn --bind 0.0.0.0:8000 msigana_ecommerce.wsgi:application"
   
networks:
  backend:

volumes:
  samiahomes_postgres_data:
